import { StyleSheet, Dimensions } from 'react-native';

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

export const style = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: screenHeight,
    minWidth: screenWidth,
    paddingTop: 40,
  },
  containerHeader: {
    position: 'relative',
    top: 40,
    width: '100%',
    height: 160,
  },
  titleContainer: {
    position: 'relative',
    width: 380,
    alignSelf: 'center',
    height: 100,
  },
  titleTextContainer: {
    position: 'relative',
    width: 280,
    height: 80,
    top: 70,
    left: 77,
  },
  textTitle: {
    fontSize: 17,
    fontFamily: 'Montserrat_600SemiBold',
  },
  subTitle: {
    width: '100%',
    paddingLeft: 20,
    gap: 10,
    fontSize: 12,
  },
  textSubTitle: {
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
    color: '#9F9F9F',
  },
  buttonContainer: {
    width: '100%',
    marginTop: 10,
    gap: 10,
  },
  button: {
    gap: 10,
    marginTop: 10,
    width: '100%',
    height: 52,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 0.5,
    borderBottomColor: '#9F9F9F',
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  buttonText: {
    fontSize: 14,
    fontFamily: 'Montserrat_500Medium',
    color: '#0C0E13',
  },
  logged: {
    backgroundColor: '#F7F7F7',
    borderBottomWidth: 0.5,
    borderBottomColor: '#9F9F9F',
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  switchContainer: {
    transform: [{ scaleX: 1 }, { scaleY: 1 }],
  },
  informationsText: {
    marginTop: 20,
  },
  title2: {
    fontSize: 14,
    fontFamily: 'Montserrat_500Medium',
    color: '#0C0E13',
  },
  marginLabel: {
    marginBottom: 6,
    marginTop: 16,
  },
  label: {
    marginLeft: 27,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    top: 18,
  },
  label2: {
    fontSize: 12,
    marginLeft: 18,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    top: 10,
  },
  containerInput: {
    width: '98%',
    height: 80,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectInput: {
    zIndex: 9999,
    borderWidth: 0.5,
    width: 350,
    height: 40,
    alignSelf: 'center',
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  inputsGroup: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    height: 100,
  },
  containerInputGroup: {
    width: '42%',
    height: 70,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputAreaGroup: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    left: 60,
    width: 162,
    height: 40,
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
  },
  containerGroup: {
    width: '50%',
    height: '100%',
    display: 'flex',
    position: 'relative',
  },
  containerGroup2: {
    width: '40%',
    height: '100%',
    display: 'flex',
  },
  inputArea: {
    borderWidth: 1,
    borderColor: '#9F9F9F',
    borderRadius: 13,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: 350,
    height: 40,
    alignSelf: 'center',
  },
  buttonContainer2: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 80,
    top: 20,
    gap: 10,
  },
  confirmButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: '#EA0356',
    marginRight: 10,
  },
  buttonTextConfirm: {
    color: '#FFFFFF',
    fontFamily: 'Montserrat_600SemiBold',
  },
  buttonTextCancel: {
    color: '#EA0356',
    fontFamily: 'Montserrat_600SemiBold',
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: '#F7F7F7',
    shadowColor: '#13151D',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 50,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 14,
    marginBottom: 15,
    textAlign: 'left',
    fontFamily: 'Montserrat_600SemiBold',
    color: '#0C0E13',
  },
  modalText: {
    marginBottom: 15,
    fontSize: 10,
    color: '#9F9F9F',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingTop: 15,
  },
  confirmButtonModal: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: '#EA0356',
    marginRight: 10,
  },
  buttonTextConfirmModal: {
    color: '#FFFFFF',
    fontFamily: 'Montserrat_600SemiBold',
  },
  buttonTextCancelMdal: {
    color: '#EA0356',
    fontFamily: 'Montserrat_600SemiBold',
  },
  cancelButtonModal: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: '#F7F7F7',
    shadowColor: '#13151D',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
});
