import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 40,
  },
  icon: {
    alignSelf: 'center',
  },
  containerPhoto: {},
  goBackButton: {
    borderRadius: 8,
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    position: 'absolute',
    top: 40,
    justifyContent: 'center',
  },
  titleContainer: {
    position: 'relative',
    width: 370,
    alignSelf: 'center',
    height: 100,
  },
  titleTextContainer: {
    position: 'relative',
    width: 280,
    height: 80,
    top: 69,
    left: 77,
  },
  textTitle: {
    fontSize: 17,
    fontFamily: 'Montserrat_600SemiBold',
  },
  dash: {
    position: 'relative',
    alignSelf: 'center',
    top: 50,
    width: 370,
    height: 100,
  },
  containerDash: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  description: {
    color: '#9F9F9F',
    fontSize: 14,
    fontFamily: 'Montserrat_500Medium',
  },
  titleDash: {
    fontSize: 13,
    position: 'relative',
    left: 20,
    color: '#9F9F9F',
  },
  nameDash: {
    fontSize: 24,
    position: 'relative',
    fontFamily: 'Montserrat_600SemiBold',
  },
  textDash: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    left: 20,
    width: '70%',
    height: '100%',
  },
  buttonNext: {
    width: 80,
    height: 60,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  containerDetails: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    top: 80,
    width: '100%',
    height: 200,
  },
  columLeft: {
    position: 'relative',
    left: 10,
    width: '40%',
    height: '100%',
  },
  titleDetails: {
    fontSize: 16,
    position: 'relative',
    left: 20,
    top: 10,
    color: '#262933',
  },
  value: {
    color: '#0C0E13',
    fontSize: 32,
    fontFamily: 'Montserrat_600SemiBold',
    left: 20,
    top: 10,
  },
  columRight: {
    width: '48%',
    display: 'flex',
    alignItems: 'flex-end',
    height: '100%',
  },
  toName: {
    color: '#9F9F9F',
    fontSize: 16,
    fontFamily: 'Montserrat_500Medium',
    left: 20,
    top: 10,
  },
  name: {
    color: '#0C0E13',
    fontSize: 16,
    fontFamily: 'Montserrat_500Medium',
    left: 20,
    top: 10,
  },
  titleValue: {
    fontSize: 27,
    position: 'relative',
    left: 20,
    color: '#000000',
    fontFamily: 'Montserrat_600SemiBold',
  },
  containerButton: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    width: '100%',
    height: 100,
  },
  button: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: 370,
    height: 60,
    borderRadius: 10,
    borderWidth: 0.4,
  },
  containerAjuda: {
    width: '90%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 60,
    position: 'relative',
    top: 60,
  },
  help: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
});
