import { Dimensions, StyleSheet } from 'react-native';
const screenWidth = Dimensions.get('window').width;

export const style = StyleSheet.create({
  container: {
    flex: 1,
    width: screenWidth,
    height: 'auto',
    paddingVertical: 40,
    paddingBottom:60,
  },
  containerHeader: {
    position: 'relative',
    width: 350,
    alignSelf: 'center',
    height: 40,
  },
  containerHeaderProgresso: {
    display: 'flex',
    flexDirection: 'row',
    position: 'relative',
    width: 90,
    height: 30,
    gap: 3,
  },
  titleContainer: {
    position: 'relative',
    width: '100%',
    height: 100,
  },
  form: {
    position: 'relative',
    top: 50,
    width: '100%',
    height: '99%',
    display: 'flex',
    justifyContent:"center",
    alignItems:"center"
  },
  textForm: {
    position: 'relative',
    left: 20,
    width: '100%',
    height: 20,
  },
  containerLabelInput : {
    width:"85%",
    height:50,
    // backgroundColor:"black"
  },
  label: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  label2: {
    marginLeft: 10,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    top: 10,
  },
  inputArea: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width:"85%",
    height: 44,
    alignSelf: 'center',
  },
  containerInput: {
    width: '100%',
    height: 44,
    alignSelf: 'center',
  },
  containerButton: {
    position: 'relative',
    top: '100%',
    width: '100%',
    height: 60,
    display: 'flex',
  },
  button: {
    width: '93%',
    height: '100%',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  inputsGroup: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: "90%",
    height: 80,
    alignSelf: 'center',
  },
  textFormGroup: {
    position: 'relative',
    left: 20,
    width: 150,
    height: 20,
  },
  containerInputGroup: {
    width: 85,
    height: 80,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputAreaGroup: {
    position: 'relative',
    left: 50,
    width: 165,
    height: 42,
    borderWidth: 0.5,
    borderColor: '#9F9F9F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  selectInput: {
    zIndex: 9999,
    borderWidth: 0.5,
    borderColor: 'black',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginLeft: 10,
    width: "95%",
  },
  containerGroup: {
    width: '50%',
    height: '100%',
    display: 'flex',
    position: 'relative',
  },
  containerUf :{
    width: "95%",
    borderWidth:0.5,
    borderColor: '#9F9F9F', 
    height: 42,
    display: 'flex',
    borderRadius:8,
    top:19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerGroup2: {
    width: '50%',
    height: '100%',
    display: 'flex',
  },
  continueButton: {
    flex: 1,
    width: 350,
    marginTop:10,
    alignSelf: 'center',
  },
});
