import { Dimensions, StyleSheet } from 'react-native';
const screenHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: 350,
    height: screenHeight,
    alignSelf: 'center',
    paddingTop: 50,
  },
  header: {
    paddingVertical: 10,
  },
  selectInput: {
    zIndex: 9999,
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: 350,
    height: 44,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    width: 350,
  },
  halfInputContainer: {
    width: 165,
  },
  halfInput: {
    borderWidth: 0.5,
    borderColor: '#9F9F9F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 15,
    fontSize: 16,
    width: 153,
  },
  bankItem: {
    padding: 20,
    fontSize: 16,
    borderRadius: 10,
  },
  backButton: {
    position: 'absolute',
    top: 80,
    left: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'white',
  },
  termsText: {
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    textAlign: 'center',
  },
  termsLink: {
    color: '#EA0356',
    textDecorationLine: 'underline',
  },
  title: {
    fontSize: 20,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    marginBottom: 20,
  },
  label: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  label2: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  input: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: 350,
    height: 44,
    alignSelf: 'center',
  },
  continueButtonContainer: {
    paddingBottom: 25,
    width: 330,
    alignSelf: 'center',
    flex: 1,
    flexDirection: 'column-reverse',
  },
  continueButton: {
    width: '100%',
    backgroundColor: '#EA0356',
    paddingVertical: 15,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: 50,
    marginTop: 20,
  },
  continueButtonText: {
    color: 'white',
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
  },
});
