import { Dimensions, StyleSheet } from 'react-native';
const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

export const style = StyleSheet.create({
  container: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop:10,
    width: screenWidth,
    height: screenHeight,
  },
  containerTopDash: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: '10%',
  },
  containerPerfil: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '50%',
    height: '100%',
    marginLeft: 30,
  },
  containerImagePerfil: {
    width: '30%',
    height: 65,
  },
  textName: {
    fontSize: 20,
    fontFamily: 'Montserrat_500Medium',
    marginLeft: 10,
  },
  containerIcons: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '20%',
    height: '100%',
    marginRight: 45,
  },
  icons: {
    marginLeft: 17,
    width: 24,
    height: 24,
  },
  painel: {
    marginTop: 6,
    display: 'flex',
    width: "85%",
    height: 131,
    backgroundColor: '#F7F7F7',
    borderRadius: 8,
  },
  eyeIcon: {
    position: 'relative',
    left: 12,
  },
  headerCard: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop:10,
    paddingVertical: 10,
    // backgroundColor:"black",
    gap: 10,
  },
  centerCard: {
    width: '90%',
    alignSelf: 'center',
  },
  bottomCard: {
    width: '90%',
    alignSelf: 'center',
    paddingVertical: 10,
  },
  saque: {
    display: 'flex',
    flexDirection: 'row',
  },
  textComission: {
    color: '#9F9F9F',
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 12,
  },
  saldo: {
    fontSize: 32,
    fontFamily: 'Montserrat_600SemiBold',
    color: '#0C0E13',
  },
  textBottom: {
    color: '#9F9F9F',
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
  },
  textSaque: {
    color: '#EA0356',
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
  },
  seta: {
    color: '#EA0356',
    fontSize: 27,
    fontFamily: 'Montserrat_500Medium',
  },
  newSimulation: {
    top: 10,
    width: "100%",
    height: 73,
    borderRadius: 10,
    backgroundColor: '#EA0356',
  },
  textSimulationContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: '70%',
    height: '100%',
    marginLeft:10,
  },
  textSimulation: {
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
    color: '#FFF',
  },
  containerButtonSimulation: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    height: '100%',
  },
  buttonAdd: {
    alignItems: 'center',
    height: '100%',
  },
  descriptionSimulation: {
    color: '#FFF',
    fontFamily: 'Montserrat_500Medium',
    fontSize: 10,
  },
  iconAdd: {
    width: 28,
    height: 28,
    top: 8,
  },
  containerTransacoes: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    top: 18,
    width: '100%',
    height: "57%",
    // backgroundColor:"black"
  },
  containerTextTransacoes:{
    width:"87%",
    height:"100%",
    // backgroundColor:'black',
  },
  textTransacoes: {
    position: 'relative',
    top: 16,
    left: 2,
    fontSize: 16,
    fontFamily: 'Montserrat_600SemiBold',
  },
  inputSearch: {
    display: 'flex',
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent:"center",
    width: "87%",
    height: 47,
    backgroundColor: '#F7F7F7',
    borderRadius: 4,
    borderWidth:0.2,
    borderColor:"black",
    position: 'relative',
    top: -2,
    // right: 16,
  },
  title: {
    display:"flex",
    justifyContent:"center",
    alignItems:"center",
    width: '100%',
    height: '10%',
  },
  iconSearch: {
    marginLeft: -5,
    alignSelf: 'center',
  },
  inputArea: {
    width: "80%",
    height:"100%",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
    fontFamily: 'Montserrat_500Medium',
  },
  scrowHorizontal: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: 400,
    height: 100,
    alignItems: 'center',
    top: -7,
  },
  containerScrow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: 446,
    height: 70,
    position: 'relative',
    top: 20,
    left: 20,
    gap: 10,
  },
  itemsScrow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#F7F7F7',
    width: 123,
    height: 39,
    borderRadius: 8,
    marginHorizontal: 10,
    gap: 10,
  },
  textBoxes: {
    color: '#9F9F9F',
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
  },
  transacoesHoje: {
    position: 'relative',
    top: 20,
    width: 370,
    height: '100%',
    flex: 1,
  },
  textDates: {
    color: '#9F9F9F',
    marginBottom: 10,
    marginLeft: 5,
    fontFamily: 'Montserrat_600SemiBold',
  },
  checkBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: 40,
    height: 40,
    marginBottom: 14,
    borderRadius: 12,
    backgroundColor: '#E8EBE9',
  },
  textBox: {
    width: 260,
    height: 60,
    position: 'relative',
    top: 12,
    left: 20,
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
  },
  boxItems: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
  },
  iconCheck: {
    padding: 10,
    backgroundColor: '#E8EBE9',
    borderRadius: 10,
    marginLeft: 11,
  },
  textHour: {
    color: '#9F9F9F',
    fontSize: 12,
    margin: 2,
    fontFamily: 'Montserrat_500Medium',
  },
  textPrice: {
    width: 260,
    height: 60,
    position: 'relative',
    top: 12,
    fontFamily: 'Montserrat_500Medium',
  },
  textTaxa: {
    color: '#9F9F9F',
    fontSize: 12,
    margin: 2,
    right: 28,
    fontFamily: 'Montserrat_500Medium',
  },
  flatList: {
    width: '100%',
    marginLeft:11,
  },
});
