import { StyleSheet, Dimensions } from 'react-native';
const screenHeight = Dimensions.get('window').height;

export const style = StyleSheet.create({
  container: {
    height: screenHeight,
    alignSelf: 'center',
    width: 390,
    paddingTop: 30,
  },
  containerBack: {
    display: 'flex',
    flexDirection: 'row',
    height: 100,
    left: 20,
  },
  titleHeader: {
    fontSize: 20,
    fontFamily: 'Montserrat_500Medium',
  },
  containerBody: {
    alignItems: 'center',
    alignSelf: 'center',
    width: 350,
  },
  dash: {
    width: 350,
    height: 140,
    backgroundColor: '#F7F7F7',
    borderRadius: 10,
  },
  buttonSaque: {
    display: 'flex',
    flexDirection: 'row',
    top: -20,
    width: 330,
    paddingVertical: 12,
    paddingHorizontal: 16,
    height: 50,
    alignItems: 'center',
    backgroundColor: '#EA0356',
    borderRadius: 10,
  },
  containerTextAndSaldo: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    left: 20,
    width: 270,
    height: 100,
  },
  textTitleDash: {
    position: 'relative',
    left: 20,
    top: 10,
    fontSize: 13,
    color: '#9F9F9F',
  },
  textSaldoDash: {
    position: 'relative',
    left: 20,
    top: 10,
    fontSize: 35,
    fontFamily: 'Montserrat_600SemiBold',
  },
  titleAndIcon: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    height: '100%',
  },
  textIcon: {
    position: 'relative',
    left: 23,
    top: -2,
    fontSize: 16,
    fontFamily: 'Montserrat_500Medium',
    color: '#FFF',
  },
  iconMoney: {
    position: 'relative',
    left: 11,
    padding: 10,
  },
  iconArrow: {
    position: 'relative',
    top: 2,
    bottom: 2,
    width: 20,
    height: 25,
    left: 23,
  },
  containerHistory: {
    display: 'flex',
    gap: 55,
    alignSelf: 'center',
    width: 350,
    minHeight: 200,
  },
  monthContainer: {
    width: 50,
    height: 100,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginHorizontal: 5,
  },
  bar: {
    width: 30,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    position: 'absolute',
    bottom: 20,
  },
  button: {
    width: '100%',
    height: 20,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  monthText: {
    color: '#000',
  },
  textTitleHistory: {
    position: 'relative',
    fontSize: 20,
    fontFamily: 'Montserrat_600SemiBold',
  },
  mon: {
    position: 'relative',
    display: 'flex',
    width: 30,
    margin: 10,
    height: 10,
    backgroundColor: '#D0D0D0',
    borderTopEndRadius: 20,
    borderTopLeftRadius: 20,
  },
  textMon: {
    position: 'relative',
    marginLeft: 13,
    color: '#D0D0D0',
    fontSize: 12,
  },
  containerHeaderTransacoes: {
    width: 390,
    height: 40,
    top: 20,
    borderBottomWidth: 1,
    display: 'flex',
    alignSelf: 'center',
    flexDirection: 'row',
    borderBottomColor: '#EEEEEE',
  },
  ContainerTitleTransacoes: {
    display: 'flex',
    flexDirection: 'row',
    gap: 6,
    position: 'relative',
    width: 123,
    height: 40,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  titleTransacoes: {
    position: 'relative',
    justifyContent: 'center',
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
  },
  iconMoneyTransacoes: {
    position: 'relative',
  },
  ContainerTitleInformacoes: {
    display: 'flex',
    flexDirection: 'row',
    position: 'relative',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: 188,
    height: 60,
    zIndex: 9999,
  },
  transacoesItems: {
    alignSelf: 'center',
    alignItems: 'center',
    width: 390,
    height: '100%',
  },
  withBorderBottom: {
    borderBottomWidth: 1,
    borderBlockColor: 'black',
  },
  iconSearchTransacoes: {
    top: 40,
  },
  containerList: {
    width: '100%',
    height: 300,
    top: 30,
  },
  contentTransactions: {
    top: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textTransacoesBody: {
    position: 'relative',
    top: 50,
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
    color: '#0C0E13',
  },
  textBodyTransacoes: {
    position: 'relative',
    top: 50,
    fontSize: 10,
    color: '#9F9F9F',
    textAlign: 'center',
    fontFamily: 'Montserrat_500Medium',
  },
  containerTransacoesBody: {
    width: 300,
    height: '100%',
  },
  listDetails: {
    alignSelf: 'center',
    flex: 1,
    borderTopColor: '#E5E5E5',
    borderTopWidth: 0.5,
    paddingTop: 10,
  },
  itemContainer: {
    justifyContent: 'space-between',
    paddingVertical: 10,
    width: 350,
    alignSelf: 'center',
  },
  textListSimple: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17.07,
    textAlign: 'left',
    color: '#0C0E13',
  },
  textListBold: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 14,
    textAlign: 'left',
    color: '#0C0E13',
  },
  flatList: {
    width: '100%',
  },
  textDates: {
    color: '#000000',
    marginBottom: 10,
    marginLeft: 22,
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 12,
  },
  checkBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: 40,
    height: 40,
    marginBottom: 14,
    borderRadius: 12,
    backgroundColor: '#E8EBE9',
  },
  textBox: {
    width: 260,
    height: 60,
    position: 'relative',
    top: 12,
    left: 20,
    fontSize: 12,
    fontFamily: 'Montserrat_600SemiBold',
  },
  boxItems: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
  },
  iconCheck: {
    padding: 10,
    backgroundColor: '#E8EBE9',
    borderRadius: 10,
    marginLeft: 11,
  },
  textHour: {
    color: '#9F9F9F',
    fontSize: 12,
    margin: 2,
    fontFamily: 'Montserrat_500Medium',
  },
  textPrice: {
    width: 260,
    height: 60,
    position: 'relative',
    top: 12,
    fontFamily: 'Montserrat_500Medium',
  },
  textTaxa: {
    color: '#9F9F9F',
    fontSize: 12,
    margin: 2,
    right: 28,
    fontFamily: 'Montserrat_500Medium',
  },
});
