import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 5,
  },
  titleContainer: {
    position: 'relative',
    width: 370,
    alignSelf: 'center',
    height: 100,
    top: 25,
  },
  titleTextContainer: {
    position: 'relative',
    width: 280,
    height: 80,
    top: 69,
    left: 77,
  },
  textTitle: {
    fontSize: 17,
    fontFamily: 'Montserrat_600SemiBold',
  },
  dash: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    top: -4,
    width: '87%',
    height: 100,
    borderRadius: 10,
    backgroundColor: '#F7F7F7',
  },
  containerDash: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  titleDash: {
    fontSize: 13,
    position: 'relative',
    left: 20,
    color: '#9F9F9F',
  },
  nameDash: {
    fontSize: 18,
    position: 'relative',
    left: 10,
    fontFamily: 'Montserrat_600SemiBold',
  },
  textDash: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    left: 20,
    width: '70%',
    height: '100%',
  },
  buttonNext: {
    width: 80,
    height: 60,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  containerDetails: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    top: 20,
    width: '100%',
    height: 200,
  },
  columLeft: {
    position: 'relative',
    left: 10,
    width: '40%',
    height: '100%',
  },
  titleDetails: {
    fontSize: 13,
    position: 'relative',
    left: 20,
    top: 10,
    color: '#000000',
  },
  columRight: {
    width: '48%',
    display: 'flex',
    alignItems: 'flex-end',
    height: '100%',
  },
  titleValue: {
    fontSize: 27,
    position: 'relative',
    left: 20,
    color: '#000000',
    fontFamily: 'Montserrat_600SemiBold',
  },
  containerButton: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    top: 30,
    width: '100%',
    height: 100,
  },
  button: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: 370,
    height: 60,
    borderRadius: 10,
    borderWidth: 0.4,
  },
  containerAjuda: {
    width: '90%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 60,
    position: 'relative',
    top: 10,
  },
  help: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
});
