import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    width: 350,
    alignSelf: 'center',
    paddingTop: 40,
  },
  title: {
    fontSize: 20,
    fontFamily: 'Montserrat_600SemiBold',
    color: 'black',
    marginVertical: 20,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  label2: {
    marginTop: 20,
    marginBottom: 5,
    marginLeft: 17,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  input: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: 350,
    height: 44,
    alignSelf: 'center',
  },
  helpText: {
    fontSize: 10,
    color: 'gray',
  },
  termsText: {
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    textAlign: 'center',
  },
  termsLink: {
    color: '#EA0356',
    textDecorationLine: 'underline',
  },
  continueButton: {
    backgroundColor: '#EA0356',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 50,
    marginBottom: 20,
    marginTop: 10,
    flexDirection: 'row',
    width: 350,
    height: 52,
    padding: 16,
    gap: 10,
  },
  continueButtonText: {
    color: 'white',
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
  },
  row: {
    flexDirection: 'row',
    width: '100%',
    gap: 10,
    display: 'flex',
    justifyContent: 'center',
  },
  halfInputContainer: {
    width: 185,
    display: 'flex',
    alignSelf: 'center',
  },
  halfInput: {
    marginBottom: 15,
    fontSize: 16,
    alignSelf: 'center',
    padding: 15,
    width: 160,
    color: 'black',
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    height: 44,
  },
  arrow: {
    marginLeft: 10,
  },
  continueButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  loginButton: {
    color: '#EA0356',
    textAlign: 'center',
    textDecorationLine: 'none',
    fontSize: 16,
    fontFamily: 'Montserrat_600SemiBold',
    marginBottom: 20,
  },
});
