import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: 'auto',
    width: 350,
    alignSelf: 'center',
    paddingTop: 30,
  },
  containerHeader: {
    position: 'relative',
    width: '100%',
    height: 100,
  },
  titleContainer: {
    position: 'relative',
    width: '100%',
    height: 100,
    top: 30,
  },
  myAdress: {
    width: 350,
    height: 93,
    borderRadius: 8,
    padding: 20,
    gap: 6,
    backgroundColor: '#F7F7F7',
    alignSelf: 'center',
  },
  myAdressTitle: {
    color: '#000000',
    fontSize: 14,
    fontFamily: 'Montserrat_600SemiBold',
  },
  myAdressDescription: {
    color: '#9F9F9F',
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
  },
  textTitle: {
    fontSize: 17,
    fontFamily: 'Montserrat_600SemiBold',
  },
  form: {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'flex',
  },
  textForm: {
    position: 'relative',
    left: 20,
    width: '100%',
    height: 20,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  label2: {
    marginTop: 20,
    marginLeft: 5,
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  input: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: 350,
    height: 44,
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    width: '100%',
    gap: 10,
    display: 'flex',
    justifyContent: 'center',
  },
  halfInputContainer: {
    width: 172,
    display: 'flex',
    alignSelf: 'center',
  },
  halfInput: {
    width: 165,
    marginBottom: 15,
    fontSize: 16,
    alignSelf: 'center',
    borderWidth: 0.5,
    borderColor: '#9F9F9F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    color: 'black',
  },
  inputArea: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: '95%',
    alignSelf: 'center',
  },
  containerInput: {
    width: '98%',
    height: 80,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerButton: {
    position: 'relative',
    top: '100%',
    width: '100%',
    height: 60,
    display: 'flex',
  },
  button: {
    width: '93%',
    height: '100%',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  inputsGroup: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    height: 100,
  },
  textFormGroup: {
    position: 'relative',
    left: 20,
    width: 150,
    height: 20,
  },
  containerInputGroup: {
    width: '48%',
    height: 80,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputAreaGroup: {
    position: 'relative',
    left: 50,
    width: 160,
    height: 56,
    borderWidth: 0.3,
    borderColor: 'black',
    borderRadius: 3,
    padding: 20,
  },
  containerGroup: {
    width: '50%',
    height: '100%',
    display: 'flex',
    position: 'relative',
  },
  containerGroup2: {
    width: '50%',
    height: '100%',
    display: 'flex',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 40,
    gap: 10,
  },
  confirmButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: '#EA0356',
    marginRight: 10,
  },
  buttonTextConfirm: {
    color: '#FFFFFF',
    fontFamily: 'Montserrat_600SemiBold',
  },
  buttonTextCancel: {
    color: '#EA0356',
    fontFamily: 'Montserrat_600SemiBold',
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 100,
    backgroundColor: '#F7F7F7',
    shadowColor: '#13151D',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
});
