export interface Bank {
  label: string;
  value: string;
}

export const banks: Bank[] = [
  { label: 'Banco do Brasil S.A.', value: '001' },
  { label: 'Banco da Amazonia S.A.', value: '003' },
  { label: 'Banco do Nordeste do Brasil S.A.', value: '004' },
  { label: 'Banco Standard de Investimentos S.A.', value: '012' },
  { label: 'Natixis Brasil S.A. Banco Múltiplo', value: '014' },
  { label: 'Banco Azteca do Brasil S.A.', value: '019' },
  { label: 'Banestes S.A. Banco do Estado do Espirito Santo', value: '021' },
  { label: 'Banco de Pernambuco S.A. - BANDEPE', value: '024' },
  { label: 'Banco Alfa S.A.', value: '025' },
  { label: 'Banco Banerj S.A.', value: '029' },
  { label: 'Banco Beg S.A.', value: '031' },
  { label: 'Banco Santander (Brasil) S.A.', value: '033' },
  { label: 'Banco Bradesco BBI S.A.', value: '036' },
  { label: 'Banco do Estado do Pará S.A.', value: '037' },
  { label: 'Banco Cargill S.A.', value: '040' },
  { label: 'Banco do Estado do Rio Grande do Sul S.A.', value: '041' },
  { label: 'Banco BVA S.A.', value: '044' },
  { label: 'Banco Opportunity S.A.', value: '045' },
  { label: 'Banco do Estado de Sergipe S.A.', value: '047' },
  { label: 'Hipercard Banco Múltiplo S.A.', value: '062' },
  { label: 'Banco IBI S.A. - Banco Múltiplo', value: '063' },
  { label: 'Banco Lemon S.A.', value: '065' },
  { label: 'Banco Morgan Stanley S.A.', value: '066' },
  { label: 'BPN Brasil Banco Múltiplo S.A.', value: '069' },
  { label: 'BRB - Banco de Brasilia S.A.', value: '070' },
  { label: 'Banco Rural Mais S.A.', value: '072' },
  { label: 'BB Banco Popular do Brasil S.A.', value: '073' },
  { label: 'Banco J. Safra S.A.', value: '074' },
  { label: 'Banco CR2 S/A', value: '075' },
  { label: 'Banco KDB do Brasil S.A.', value: '076' },
  { label: 'Banco Intermedium S/A', value: '077' },
  { label: 'BES Investimento do Brasil S.A. - Banco de Investimento', value: '078' },
  { label: 'JBS Banco S/A', value: '079' },
  { label: 'Concórdia Banco S.A.', value: '081' },
  { label: 'Banco Topázio S.A.', value: '082' },
  { label: 'Banco da China Brasil S.A', value: '083' },
  { label: 'Banco BM&F de Serviços de Liquidação e Custódia S.A.', value: '096' },
  { label: 'Caixa Economica Federal', value: '104' },
  { label: 'Banco BBM S/A', value: '107' },
  { label: 'Banco Nossa Caixa S.A.', value: '151' },
  { label: 'Banco Itaú BBA S.A.', value: '184' },
  { label: 'Banco Bradesco Cartões S.A.', value: '204' },
  { label: 'Banco UBS Pactual S.A.', value: '208' },
  { label: 'Banco Matone S.A.', value: '212' },
  { label: 'Banco Arbi S.A.', value: '213' },
  { label: 'Banco Dibens S.A.', value: '214' },
  { label: 'Banco Comercial e de Investimento Sudameris S.A.', value: '215' },
  { label: 'Banco John Deere S.A.', value: '217' },
  { label: 'Banco Bonsucesso S.A.', value: '218' },
  { label: 'Banco Calyon Brasil S.A.', value: '222' },
  { label: 'Banco Fibra S.A.', value: '224' },
  { label: 'Banco Brascan S.A.', value: '225' },
  { label: 'Banco Cruzeiro do Sul S.A.', value: '229' },
  { label: 'Unicard Banco Múltiplo S.A.', value: '230' },
  { label: 'Banco GE Capital S.A.', value: '233' },
  { label: 'Banco Bradesco S.A.', value: '237' },
  { label: 'Banco Classico S.A.', value: '241' },
  { label: 'Banco Máxima S.A.', value: '243' },
  { label: 'Banco ABC Brasil S.A.', value: '246' },
  { label: 'Banco Boavista Interatlantico S.A.', value: '248' },
  { label: 'Banco Investcred Unibanco S.A.', value: '249' },
  { label: 'Banco Schahin S.A.', value: '250' },
  { label: 'Paraná Banco S.A.', value: '254' },
  { label: 'Banco Cacique S.A.', value: '263' },
  { label: 'Banco Fator S.A.', value: '265' },
  { label: 'Banco Cédula S.A.', value: '266' },
  { label: 'Banco de la Nacion Argentina', value: '300' },
  { label: 'Banco BMG S.A.', value: '318' },
  { label: 'Banco Industrial e Comercial S.A.', value: '320' },
  { label: 'Banco Itaú S.A.', value: '341' },
  { label: 'Banco Societe Generale Brasil S.A.', value: '366' },
  { label: 'Banco WestLB do Brasil S.A.', value: '370' },
  { label: 'Banco J.P. Morgan S.A.', value: '376' },
  { label: 'Banco Mercantil do Brasil S.A.', value: '389' },
  { label: 'Banco Finasa BMC S.A.', value: '394' },
  { label: 'HSBC Bank Brasil S.A. - Banco Múltiplo', value: '399' },
  { label: 'Unibanco-União de Bancos Brasileiros S.A.', value: '409' },
  { label: 'Banco Capital S.A.', value: '412' },
  { label: 'Banco Safra S.A.', value: '422' },
  { label: 'Banco Rural S.A.', value: '453' },
  { label: 'Banco de Tokyo-Mitsubishi UFJ Brasil S/A', value: '456' },
  { label: 'Banco Sumitomo Mitsui Brasileiro S.A.', value: '464' },
  { label: 'Banco Caixa Geral - Brasil S.A.', value: '473' },
  { label: 'Citibank N.A.', value: '477' },
  { label: 'Banco Itaubank S.A.', value: '479' },
  { label: 'Deutsche Bank S.A. - Banco Alemao', value: '487' },
  { label: 'JPMorgan Chase Bank, National Association', value: '488' },
  { label: 'ING Bank N.V.', value: '492' },
  { label: 'Banco de la Republica Oriental del Uruguay', value: '494' },
  { label: 'Banco de la Provincia de Buenos Aires', value: '495' },
  { label: 'Banco Credit Suisse (Brasil) S.A.', value: '505' },
  { label: 'Banco Luso Brasileiro S.A.', value: '600' },
  { label: 'Banco Industrial do Brasil S.A.', value: '604' },
  { label: 'Banco VR S.A.', value: '610' },
  { label: 'Banco Paulista S.A.', value: '611' },
  { label: 'Banco Guanabara S.A.', value: '612' },
  { label: 'Banco Pecunia S.A.', value: '613' },
  { label: 'Banco Panamericano S.A.', value: '623' },
  { label: 'Banco Ficsa S.A.', value: '626' },
  { label: 'Banco Intercap S.A.', value: '630' },
  { label: 'Banco Rendimento S.A.', value: '633' },
  { label: 'Banco Triangulo S.A.', value: '634' },
  { label: 'Banco Sofisa S.A.', value: '637' },
  { label: 'Banco Prosper S.A.', value: '638' },
  { label: 'Banco Alvorada S.A.', value: '641' },
  { label: 'Banco Pine S.A.', value: '643' },
  { label: 'Itaú Unibanco Banco Múltiplo S.A.', value: '652' },
  { label: 'Banco Indusval S.A.', value: '653' },
  { label: 'Banco A.J. Renner S.A.', value: '654' },
  { label: 'Banco Votorantim S.A.', value: '655' },
  { label: 'Banco Daycoval S.A.', value: '707' },
  { label: 'Banif - Banco Internacional do Funchal (Brasil), S.A.', value: '719' },
  { label: 'Banco Credibel S.A.', value: '721' },
  { label: 'Banco Gerdau S.A', value: '734' },
  { label: 'Banco Pottencial S.A.', value: '735' },
  { label: 'Banco Morada S.A', value: '738' },
  { label: 'Banco BGN S.A.', value: '739' },
  { label: 'Banco Barclays S.A.', value: '740' },
  { label: 'Banco Ribeirao Preto S.A.', value: '741' },
  { label: 'Banco Semear S.A.', value: '743' },
  { label: 'Banco Citibank S.A.', value: '745' },
  { label: 'Banco Modal S.A.', value: '746' },
  { label: 'Banco Rabobank International Brasil S.A.', value: '747' },
  { label: 'Banco Cooperativo Sicredi S.A.', value: '748' },
  { label: 'Banco Simples S.A.', value: '749' },
  { label: 'Dresdner Bank Brasil S.A. Banco Múltiplo', value: '751' },
  { label: 'Banco BNP Paribas Brasil S.A.', value: '752' },
  { label: 'NBC Bank Brasil S.A. - Banco Múltiplo', value: '753' },
  { label: 'Banco Cooperativo do Brasil S.A. - BANCOOB', value: '756' },
  { label: 'Banco KEB do Brasil S.A.', value: '757' },
  { label: 'Nubank', value: '260' },
  { label: 'Inter', value: '77' },
  { label: 'Santander', value: 'santander' },
  { label: 'Next', value: '237' },
  { label: 'C6 Bank', value: '336' },
  { label: 'Banco Original', value: '212' },
  { label: 'Banco Neon', value: '799' },
  { label: 'PicPay (conta de pagamento)', value: '380' },
  { label: 'Mercado Pago (conta de pagamento)', value: '323' },
  { label: 'Banco BTG Pactual', value: '208' },
  { label: 'Banco Banrisul', value: '41' },
  { label: 'Banco Sicoob', value: '985' },
  { label: 'N26', value: '785' },
  { label: 'Revolut', value: '996' },
];
