import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    width: 370,
    alignSelf: 'center',
    height: 'auto',
    paddingTop: 40,
  },
  containerHeader: {
    position: 'relative',
    width: 350,
    alignSelf: 'center',
    height: 40,
    paddingTop: 40,
    paddingBottom: 40,
  },
  containerHeaderProgresso: {
    display: 'flex',
    flexDirection: 'row',
    position: 'relative',
    height: 40,
    gap: 3,
  },
  containerLabelTextInput:{
    width:"94%",
  },
  selectInput: {
    zIndex: 9999,
    // borderWidth: 0.3,
    borderColor: '#9F9F9F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: 350,
    height: 42,
    marginTop:-11,
    alignSelf: 'center',
  },
  typePixSelect: {
    zIndex: 9999,
    borderWidth: 0.3,
    borderColor: '#9F9F9F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: 150,
    height: 42,
    alignSelf: 'center',
  },
  label: {
    marginTop: 20,
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
  },
  label2: {
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
    color: 'black',
    top: 10,
  },
  barraUmPorCento: {
    width: 125,
    height: 20,
    backgroundColor: '#F7F7F7',
    borderRadius: 10,
  },
  titleContainer: {
    width: '100%',
    height: 40,
  },
  titleTextContainer: {
    position: 'relative',
    width: 280,
    height: 80,
    top: 69,
    left: 77,
  },
  textTitle: {
    fontSize: 17,
    fontFamily: 'Montserrat_600SemiBold',
  },
  form: {
    position: 'relative',
    paddingTop: 40,
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems:"center"
  },
  inputAreaPix: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: 200,
    height: 44,
    alignSelf: 'center',
  },
  inputArea: {
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    width: 350,
    height: 44,
    alignSelf: 'center',
  },
  containerInput: {
    width: '98%',
    borderWidth: 0.5,
    borderColor: '#0C0E13',
    borderRadius: 8,
    height: 45,
    display: 'flex',
    justifyContent: 'center',
    marginTop:5,
    alignItems: 'center',
  },
  containerButton: {
    position: 'relative',
    top: '100%',
    width: '100%',
    height: 60,
    display: 'flex',
  },
  button: {
    width: '93%',
    height: '100%',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  inputsGroup: {
    flexDirection: 'row',
    width: 350,
    height: 100,
  },
  inputsGroupType: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 350,
    height: 100,
  },
  containerInputGroup: {
    width: '100%',
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputAreaGroupCheck: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputAreaGroup: {
    alignSelf: 'center',
    width: 165,
    borderWidth: 0.5,
    borderRadius: 8,
    borderColor: '#0C0E13',
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: 'black',
    height: 44,
  },
  textInputCheck: {
    position: 'relative',
    left: 10,
    fontSize: 12,
  },
  containerGroup: {
    width: '50%',
  },
  checkbox: {
    width: 10,
    height: 10,
  },
  continueButton: {
    flex: 1,
    width: 350,
    height: 200,
    alignSelf: 'center',
    flexDirection: 'column-reverse',
    paddingVertical: 20,
  },
});
